export const COUNTRY_TIMEZONES: Record<string, string> = {
  "United States": "America/New_York",
  "United Kingdom": "Europe/London",
  "Germany": "Europe/Berlin",
  "France": "Europe/Paris",
  "Australia": "Australia/Sydney",
  "Canada": "America/Toronto",
  "Nigeria": "Africa/Lagos",
  "India": "Asia/Kolkata",
  "China": "Asia/Shanghai",
  "Japan": "Asia/Tokyo",
  "Brazil": "America/Sao_Paulo",
  "South Africa": "Africa/Johannesburg",
  "UAE": "Asia/Dubai",
  "Saudi Arabia": "Asia/Riyadh",
  "Kenya": "Africa/Nairobi",
  "Ghana": "Africa/Accra",
  "Mexico": "America/Mexico_City",
  "Italy": "Europe/Rome",
  "Spain": "Europe/Madrid",
  "Netherlands": "Europe/Amsterdam",
  "Switzerland": "Europe/Zurich",
  "Sweden": "Europe/Stockholm",
  "Norway": "Europe/Oslo",
  "Denmark": "Europe/Copenhagen",
  "Poland": "Europe/Warsaw",
  "Russia": "Europe/Moscow",
  "Turkey": "Europe/Istanbul",
  "Egypt": "Africa/Cairo",
  "Pakistan": "Asia/Karachi",
  "Bangladesh": "Asia/Dhaka",
  "Indonesia": "Asia/Jakarta",
  "Malaysia": "Asia/Kuala_Lumpur",
  "Singapore": "Asia/Singapore",
  "Philippines": "Asia/Manila",
  "Thailand": "Asia/Bangkok",
  "Vietnam": "Asia/Ho_Chi_Minh",
  "South Korea": "Asia/Seoul",
  "New Zealand": "Pacific/Auckland",
  "Argentina": "America/Argentina/Buenos_Aires",
  "Chile": "America/Santiago",
  "Colombia": "America/Bogota",
  "Peru": "America/Lima",
  "Portugal": "Europe/Lisbon",
  "Belgium": "Europe/Brussels",
  "Austria": "Europe/Vienna",
  "Czech Republic": "Europe/Prague",
  "Hungary": "Europe/Budapest",
  "Romania": "Europe/Bucharest",
  "Greece": "Europe/Athens",
  "Israel": "Asia/Jerusalem",
  "Iran": "Asia/Tehran",
  "Iraq": "Asia/Baghdad",
  "Kuwait": "Asia/Kuwait",
  "Qatar": "Asia/Qatar",
  "Ethiopia": "Africa/Addis_Ababa",
  "Tanzania": "Africa/Dar_es_Salaam",
  "Uganda": "Africa/Kampala",
  "Cameroon": "Africa/Douala",
  "Ivory Coast": "Africa/Abidjan",
  "Senegal": "Africa/Dakar",
  "Morocco": "Africa/Casablanca",
  "Algeria": "Africa/Algiers",
  "Tunisia": "Africa/Tunis",
  "Angola": "Africa/Luanda",
};

export const COUNTRY_LIST = Object.keys(COUNTRY_TIMEZONES).sort();

export function getTimezoneForCountry(country: string): string {
  return COUNTRY_TIMEZONES[country] || "America/New_York";
}